CarRental/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarRental.Models
{
    public class Client
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string PhonehoneNumber { get; set; }
        public string Email { get; set; }




        public virtual ClientCard ClientCard { get; set; }
    }
}

CarRental/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarRental.Data;
using CarRental.Models;
using CarRental.Interfaces;
using CarRental.ViewModels.CarModels;
using CarRental.ViewModels.CheckoutModels;

namespace CarRental.Controllers
{
    public class CarsController : Controller
    {
        private ICar _cars;
        private ICheckout _checkouts;

        private ApplicationDbContext _context;

        public CarsController(ApplicationDbContext context, ICar cars, ICheckout checkouts)
        {
            _context = context;
            _cars = cars;
            _checkouts = checkouts;
        }

        // /Cars/Index

        public IActionResult Index()
        {
            var carModels = _cars.GetAll();
            var listingResult = carModels
                .Select(result => new CarIndexListingModel
                {
                    Id = result.Id,
                    Manufacturer = _cars.GetManufacturer(result.Id),
                    Model = _cars.GetModel(result.Id),
                    Year = _cars.GetYear(result.Id).ToString()

                });

            var model = new CarIndexModel()
            {
                Cars = listingResult
            };


            return View(model);

        }





        public IActionResult Details(int id)
        {
            var car = _cars.GetById(id);



            var model = new CarDetailsModel
            {
                CarId = id,
                Model = car.Model,
                Manufacturer = car.Manufacturer,
                Cost = car.Cost,
                Status = car.Status.Name,
                CheckoutHistory = _checkouts.GetCheckoutHistory(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                ClientName = _checkouts.GetCurrentCheckoutClient(id),
                ReturnDate = _checkouts.GetCurrentCheckoutReturn(id),
                NumberOfDays = _checkouts.GetNumberOfDays(id),
                TotalCost = _checkouts.GetTotalCost(id),


            };

            return View(model);

        }



        public IActionResult Checkout(int id)
        {
            var car = _cars.GetById(id);
            var model = new CheckoutModel
            {
                CarId = id,
                Manufacturer = car.Manufacturer,
                Model = car.Model,
                ClientCardId = "",

                IsCheckedOut = _checkouts.IsCheckedOut(id)
            };
            return View(model);
        }

        public IActionResult CheckIn(int id)
        {
            _checkouts.CheckInItem(id);
            return RedirectToAction("Details", new { id = id });
        }

        public IActionResult MarkDamaged(int id)
        {
            _checkouts.MarkDamaged(id);
            return RedirectToAction("Details", new { id = id });

        }
        public IActionResult MarkRepaired(int id)
        {
            _checkouts.MarkRepaired(id);
            return RedirectToAction("Details", new { id = id });

        }




        [HttpPost]
        public IActionResult PlaceCheckout(int carId, int clientCardId, DateTime returnTime)
        {
            _checkouts.CheckOutItem(carId, clientCardId, returnTime);
            return RedirectToAction("Details", new { id = carId });
        }



   





        //// GET: Cars
        //public async Task<IActionResult> Index()
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Cars.ToListAsync());
        //}

        //// GET: Cars/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var car = await _context.Cars
        //        .Include(s => s.Status)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (car == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(car);
        //}

        //// GET: Cars/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Cars/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Manufacturer,Model,Year,Cost")] Car car)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(car);


        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(car);
        //}

        //// GET: Cars/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var car = await _context.Cars.FindAsync(id);
        //    if (car == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(car);
        //}

        //// POST: Cars/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Manufacturer,Model,Year,Cost")] Car car)
        //{
        //    if (id != car.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(car);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!CarExists(car.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(car);
        //}

        //// GET: Cars/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var car = await _context.Cars
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (car == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(car);
        //}

        //// POST: Cars/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var car = await _context.Cars.FindAsync(id);
        //    _context.Cars.Remove(car);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool CarExists(int id)
        //{
        //    return _context.Cars.Any(e => e.Id == id);
        //}
    }
}

CarRental/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRental.Interfaces;
using CarRental.ViewModels.ClientModels;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.Controllers
{
    public class ClientsController : Controller
    {
        private IClient _client;

        public ClientsController(IClient client)
        {
            _client = client;
        }



        public IActionResult Index()
        {

            var clients = _client.GetAll();

            var clientListings = clients.Select(c => new ClientDetailsModel
            {
                Id = c.Id,
                FirstName = c.FirstName,
                LastName = c.LastName,
                ClientCardId = c.ClientCard.Id,
                OverdueFees = c.ClientCard.Fees,
                

            }).ToList();


            var model = new ClientIndexModel()
            {
                Clients = clientListings
            };

            return View(model);
        }


        public IActionResult Details(int id)
        {
            var client = _client.Get(id);

            var model = new ClientDetailsModel
            {
                Id = client.Id,
                LastName = client.LastName,
                FirstName = client.FirstName,
                Address = client.Address,
                MemberSince = client.ClientCard.Created,
                OverdueFees = client.ClientCard.Fees,
                ClientCardId = client.ClientCard.Id,
                Telephone = client.PhonehoneNumber,
                CarsCheckedOut = _client.GetCheckouts(id),
                CheckoutHistory = _client.GetCheckoutHistory(id)


            };

            return View(model);
        }


    }
}

CarRental/Views/Clients/Details.cshtml
@model CarRental.ViewModels.ClientModels.ClientDetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Client Details</h2>

<div class="row">
    <div class="col-lg-4">
        <div>
            <h2>@Model.FirstName @Model.LastName</h2>
            <div>
                <div>Client Card ID: @Model.ClientCardId</div>
                <div>Address: @Model.Address</div>
                <div>Phone number: @Model.Telephone</div>
                <div>Member Since: @Model.MemberSince</div>
                @*@if (@Model.OverdueFees > 0)
                    {
                        <div id="patronHasFees">Current Fees Due: $@Model.OverdueFees</div>
                    }
                    else
                    {
                        <div id="patronNoFees">No Fees Currently Due.</div>

                    }*@
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <h4>Cars Currently Rented Out</h4>
        @if (@Model.CarsCheckedOut.Any())
        {
            <div>

                @foreach (var checkout in @Model.CarsCheckedOut)
                {


                    <div class="panel panel-primary">
                        <div class="panel-heading">   @checkout.Car.Manufacturer @checkout.Car.Model  - (Car ID: @checkout.Car.Id)</div>
                        <div class="panel-body">
                            Since: @checkout.Since
                            <br />
                            To: @checkout.Until
                            <br/>

                            <a class="btn btn-block btn-success" asp-controller="Cars" asp-action="Details" asp-route-id="@checkout.Car.Id">Check In</a>

                        </div>
                    </div>






                }

            </div>
        }
        else
        {
            <div>No cars currently rented out.</div>

        }
    </div>





    <div class="col-lg-4">
        <h4>Previously rented cars</h4>
        @if (@Model.CheckoutHistory.Any())
        {
    <div>

        @foreach (var checkout in @Model.CheckoutHistory)
        {

            <div class="panel panel-warning">
                <div class="panel-heading"> @checkout.Car.Manufacturer  @checkout.Car.Model - (Car ID: @checkout.Car.Id) </div>
                <div class="panel-body">
                    Rented Out: @checkout.CheckedOut
                    <br />
                    Rented to @checkout.ReturnDate
                    <br />
                    Returned  @checkout.CheckedIn
                    <br />
                    <a class="btn btn-block btn-info" asp-controller="Cars" asp-action="Details" asp-route-id="@checkout.Car.Id">Go to Car </a>

                </div>
            </div>

        }

    </div>
        }
        else
        {
            <div> No history</div>

        }
    </div>


</div>

CarRental/Views/Clients/Index.cshtml
@model  CarRental.ViewModels.ClientModels.ClientIndexModel

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<table class="table table-bordered table-hover" id="patronIndexTable">
    <thead>
        <tr>
            <th>
                Profile Link
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>

            <th>
                Library card id
            <th>
                Overdue Fees
            </th>
            <th> Home library</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Clients)
        {
            <tr>
                <td></td>
                <td>
                    <a asp-controller="Clients" asp-action="Details" asp-route-id="@item.Id"> Details</a>
                </td>
                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.ClientCardId
                </td>
                <td>
                    @item.OverdueFees
                </td>
                <td>
                    @* @item.HomeLibraryBranch*@
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>